"""
Integration module to connect pattern visualization with the chart module.

This module provides functions for seamlessly integrating ML-detected patterns
with the existing candlestick chart generation from chart.py.
"""

import io
import base64
from typing import Dict, List, Tuple, Any

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.figure import Figure

from wave.patterns import PatternType, PatternMatch, detect_patterns
from wave.ml.viz.pattern_viz import PatternVisualizer


def draw_chart_with_patterns(
    df: pd.DataFrame,
    patterns: Dict[PatternType, List[PatternMatch]] = None,
    title: str = None,
    figsize: Tuple[int, int] = (12, 8),
    pattern_visualizer: PatternVisualizer = None,
    as_data_url: bool = False
) -> str:
    """Draw candlestick chart with pattern overlays.

    Args:
        df: DataFrame with OHLCV data
        patterns: Dictionary of pattern matches (if None, will detect patterns)
        title: Chart title
        figsize: Figure size as (width, height) tuple
        pattern_visualizer: Optional custom PatternVisualizer instance
        as_data_url: If True, return as data URL format

    Returns:
        Base64 encoded PNG image (or data URL if as_data_url is True)
    """
    # If no patterns provided, detect them
    if patterns is None:
        patterns = detect_patterns(df)

    # Use provided visualizer or create new one
    visualizer = pattern_visualizer or PatternVisualizer()

    # Generate chart with patterns
    img_str = visualizer.draw_patterns_on_chart(df, patterns, title, figsize)

    # Convert to data URL if requested
    if as_data_url and not img_str.startswith('data:'):
        img_str = f"data:image/png;base64,{img_str}"

    return img_str


def overlay_patterns_on_existing_chart(
    chart_img_data: str,
    df: pd.DataFrame,
    patterns: Dict[PatternType, List[PatternMatch]],
    figsize: Tuple[int, int] = (12, 8),
    title: str = "Chart with Detected Patterns"
) -> str:
    """Overlay patterns on an existing chart image.

    This is useful when you have an existing chart generated by another system
    and want to add pattern overlays without regenerating the chart.

    Args:
        chart_img_data: Base64 encoded chart image or data URL
        df: DataFrame with OHLCV data (used for alignment)
        patterns: Dictionary of pattern matches
        figsize: Figure size as (width, height) tuple
        title: Chart title

    Returns:
        Base64 encoded PNG image with pattern overlays
    """
    # Extract base64 data if in data URL format
    if chart_img_data.startswith('data:'):
        chart_img_data = chart_img_data.split('base64,')[1]

    # Decode the image
    img_bytes = base64.b64decode(chart_img_data)
    img_buf = io.BytesIO(img_bytes)

    # Create a new figure to display the image
    fig = Figure(figsize=figsize)
    ax = fig.add_subplot(111)

    # Display the original chart image
    img = plt.imread(img_buf)
    ax.imshow(img)
    ax.axis('off')  # Hide axis

    # Create a transparent overlay for patterns
    overlay_fig = Figure(figsize=figsize, dpi=100)
    overlay_ax = overlay_fig.add_subplot(111)

    # Make the background transparent
    overlay_fig.patch.set_alpha(0)
    overlay_ax.patch.set_alpha(0)

    # Create x range matching the data length
    x = np.arange(len(df))

    # Set axis limits to match the dataset
    y_min = df['low'].min() * 0.98
    y_max = df['high'].max() * 1.02
    overlay_ax.set_xlim(0, len(df)-1)
    overlay_ax.set_ylim(y_min, y_max)

    # Use pattern visualizer to overlay patterns
    visualizer = PatternVisualizer()
    for pattern_type, pattern_list in patterns.items():
        for pattern in pattern_list:
            visualizer.overlay_pattern(overlay_ax, pattern, df)

    # Convert overlay to image
    overlay_buf = io.BytesIO()
    overlay_fig.savefig(overlay_buf, format='png', dpi=100, transparent=True)
    overlay_buf.seek(0)

    # Convert to base64 for return
    overlay_img_str = base64.b64encode(overlay_buf.read()).decode('utf-8')

    # Close figures to free memory
    plt.close(fig)
    plt.close(overlay_fig)

    return overlay_img_str


def augment_chart_with_ml_patterns(
    df: pd.DataFrame,
    ml_predictions: List[Dict[str, Any]],
    confidence_threshold: float = 0.5,
    title: str = None,
    figsize: Tuple[int, int] = (12, 8)
) -> str:
    """Generate chart with ML-predicted patterns.

    Args:
        df: DataFrame with OHLCV data
        ml_predictions: List of dictionaries with ML model predictions
            Each prediction should have:
            - 'pattern_type': PatternType enum
            - 'start_idx': Start index in dataframe
            - 'end_idx': End index in dataframe
            - 'confidence': Confidence score (0-1)
            - 'metadata': Optional additional info
        confidence_threshold: Minimum confidence to show pattern
        title: Chart title
        figsize: Figure size as (width, height) tuple

    Returns:
        Base64 encoded PNG image with pattern overlays
    """
    # Convert ML predictions to PatternMatch objects
    patterns = {}

    for pred in ml_predictions:
        # Skip if below confidence threshold
        if pred.get('confidence', 0) < confidence_threshold:
            continue

        pattern_type = pred['pattern_type']
        if pattern_type not in patterns:
            patterns[pattern_type] = []

        # Create PatternMatch from prediction
        pattern = PatternMatch(
            pattern_id=f"ml_{len(patterns[pattern_type])}",
            pattern_type=pattern_type,
            score=pred.get('confidence', 0.5),
            start_idx=pred['start_idx'],
            end_idx=pred['end_idx'],
            bars_matched=pred['end_idx'] - pred['start_idx'] + 1,
            indicator_scores=pred.get('indicator_scores', None)
        )

        patterns[pattern_type].append(pattern)

    # Generate chart with patterns
    return draw_chart_with_patterns(
        df=df,
        patterns=patterns,
        title=title or "Chart with ML-Detected Patterns",
        figsize=figsize
    )
