{
 "title": "WaveSeer Metrics",
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "rate(http_server_requests_total[1m])",
     "legendFormat": "{{status}} {{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 6 },
   "targets": [
    { "expr": "process_cpu_seconds_total" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 6 },
   "targets": [
    { "expr": "process_resident_memory_bytes" }
   ]
  }
 ]
}